concurrent = 3
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "building installer"
  url = "https://gitlab.com/"
  token = "mytokenhere"
  executor = "shell"
  builds_dir = "C:\\Users\\Administrator\\Desktop\\ci-cd"
  output_limit = 10240
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
